import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :blau_drill, BlauDrillWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Disable LiveSvelte SSR in production by default. This is a single-operator
# desktop app served over loopback; SSR adds a Node sidecar process that is not
# needed for first-paint here. Flip to `ssr: true` if you want server-rendered
# Svelte and have the SSR build (priv/svelte) deployed.
config :live_svelte, ssr: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
